name: SPLINES - C^0 CONTINUITY

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------------- WINDOWS ----------------
      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          choco install mingw -y
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install raylib:x64-mingw-static
          mkdir build -Force
          g++ src/main.cpp -std=c++17 -Wall -Wextra -o build/main.exe `
            -I vcpkg\installed\x64-mingw-static\include `
            -L vcpkg\installed\x64-mingw-static\lib `
            -lraylib -lglfw3 -lopengl32 -lgdi32 -lwinmm
      - name: Upload Windows build
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/main.exe

      # ---------------- macOS ----------------
      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install raylib
          mkdir -p build
          clang++ src/main.cpp -std=c++17 -o build/main \
            -I/opt/homebrew/include \
            -L/opt/homebrew/lib \
            -lraylib \
            -framework OpenGL \
            -framework Cocoa \
            -framework IOKit \
            -framework CoreVideo
      - name: Upload macOS build
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/main

      # ---------------- Linux ----------------
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libasound2-dev \
            pkg-config

      - name: Build (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install raylib
          mkdir -p build
          g++ src/main.cpp -std=c++17 -Wall -Wextra -o build/main \
            -I vcpkg/installed/x64-linux/include \
            -L vcpkg/installed/x64-linux/lib \
            -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
      - name: Upload Linux build
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/main
